apiVersion: apps/v1
kind: Deployment
metadata:
  name: keynetra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keynetra
  template:
    metadata:
      labels:
        app: keynetra
    spec:
      containers:
        - name: keynetra
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
