apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keynetra
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: keynetra.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keynetra
                port:
                  number: 8000
