apiVersion: v1
kind: Service
metadata:
  name: keynetra
  labels:
    app: keynetra
spec:
  selector:
    app: keynetra
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
